version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:17
    container_name: postgres_event_sys
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - event_sys_network
    restart: unless-stopped

networks:
  event_sys_network:
    driver: bridge

volumes:
  postgres_data:
    name: postgres_event_sys_data
